[package]
name = "ticketland-pass-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
eyre = "0.6.8"
serenity = "0.11.5"
tokio = { version = "1.14.1", features = ["rt-multi-thread"]}
tracing = "0.1.19"
